using System;

namespace Gehtsoft.Xce.TextBuffer
{
    /// <summary>
    /// Callback interface for text buffer change notifications
    /// </summary>
    public interface ITextBufferCallback
    {
        /// <summary>
        /// Called when one or more lines are inserted into the buffer
        /// </summary>
        /// <param name="lineIndex">The index where lines were inserted</param>
        /// <param name="count">The number of lines inserted</param>
        void OnLinesInserted(int lineIndex, int count);

        /// <summary>
        /// Called when one or more lines are deleted from the buffer
        /// </summary>
        /// <param name="lineIndex">The index where lines were deleted</param>
        /// <param name="count">The number of lines deleted</param>
        void OnLinesDeleted(int lineIndex, int count);

        /// <summary>
        /// Called when a substring is inserted into a line
        /// </summary>
        /// <param name="lineIndex">The line index</param>
        /// <param name="columnIndex">The column index where the substring was inserted</param>
        /// <param name="length">The length of the inserted substring</param>
        void OnSubstringInserted(int lineIndex, int columnIndex, int length);

        /// <summary>
        /// Called when a substring is deleted from a line
        /// </summary>
        /// <param name="lineIndex">The line index</param>
        /// <param name="columnIndex">The column index where the substring was deleted</param>
        /// <param name="length">The length of the deleted substring</param>
        void OnSubstringDeleted(int lineIndex, int columnIndex, int length);

        /// <summary>
        /// Called immediately before the buffer flushes the queued events that were
        /// generated by a single <see cref="TextBuffer.Undo"/> or <see cref="TextBuffer.Redo"/>.
        /// During replay the buffer suppresses Owner fan-out and queues every On*Inserted /
        /// On*Deleted event; this method, the queued events, and <see cref="OnReplayEnd"/>
        /// together delimit one atomic replay batch from the Owner's perspective.
        /// <para>
        /// Useful for: pausing UI repaint, switching syntax highlighting into a "bulk
        /// update" mode, suppressing diagnostics recomputation, etc. Always paired with
        /// <see cref="OnReplayEnd"/> via try/finally if this method returns normally.
        /// </para>
        /// </summary>
        void OnReplayBegin() { }

        /// <summary>
        /// Called after the queued replay events have been delivered (or after one of
        /// them threw — runs in a finally). Always paired with a prior successful
        /// <see cref="OnReplayBegin"/>.
        /// </summary>
        void OnReplayEnd() { }
    }
}
